### PR TITLE
Set nfs-mounted label selector where custom mounts are used

### PR DESCRIPTION
**Pull request by supertassu**

### CODE REVIEW

**Review by lucaswerkmeister — COMMENTED** [review]
Hm, is there a reason this doesn’t include the `function-orchestrator` and `update` deployments? I think those also need NFS.

**Comment by supertassu** [comment]
Those automount everything via `toolforge: tool`, which will do this automatically. The components this patch modifies mount NFS volumes manually.

**Comment by lucaswerkmeister** [comment]
I see… but that only applies to `update`, I think? `function-orchestrator` doesn’t have `toolforge: tool`. (The orchestrator deployment also tweaks the mounts.)

**Comment by supertassu** [comment]
Oh, indeed! Fixed.

**Review by lucaswerkmeister — APPROVED** [review]

**Comment by lucaswerkmeister** [comment]
Thanks!

**Pull request merged**
